Repository pritamworld/MAD3463_Sample, pull requests merged in 2019-01, with the labels that each got.

#3 New String Code is added
  MandeepKaur/StringDemo.java
  MandeepKaur/new 1.txt
Labels: bug

#6 Emil
  emil/emil.txt
Labels: good first issue

#7 prabhjot c0747580.....
  prabhjot/c0747580.txt
Labels: help wanted

#8 sum
  sooraj/sooraj.txt
Labels: enhancement

#9 this is my file
  SAMIR/samir.txt
Labels: bug

#20 Create eshwaraj
  eshwaraj
Labels: bug
